如何测试确保一个异步函数一定会失败

写法一

```ad-warning
如果代码中出现了 catch 一定要 `expect.assertions(次数)` 确保 catch 中的expect 一定会执行
```

```ts
test("fetchData 返回结果为 404", ()=>{
	// !!保证 catch 中的 expect 一定会走
	expect.assertions(1);
	return fetchData().catch((e)=>{
		expect(e.toString().indexOf('404')>-1).toBe(true)
	})	
})
```

写法二

注：[[匹配器#toMatchObject|toMatchObj]]

```ts
test("fetchData 返回的结果为一个 response", ()=>{
	return expect(fetchData()).resolve.toMatchObj({
	data:{
		success:true;
	}	
	})
})

test("fetchData 返回结果为 404", ()=>{
	return expect(fetchData()).reject.toThrow();
})
```